language: java
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: G0+r5OVOATaGKAN8yeTFNLtjbfRDvtSwijRAU+L7+wDKKv55RfV17QUCiP2r6c0nAsy4qud0DyNGUOO33NUcxbjXEMsXndDcxcrOCte6G9Ysv9+8y9oTqM474ja72gYm3M3rczZ9sBccmpzh0RQvGWsAZI+ZAw0YbohuXhgULvZg6dL/gMKyOlHeDRA29R6Mk1tPD+apY3y+IFlXVxXIl/rDq+OZnlB3+ZqGsb9MHkvEkQ1I8FIQLBWxoDp2oGW6boN1NA3vNgl9yx64HahvCempo4ZzBEp9nCeGHCzDXfMurvcS1kzkjI7uxzrxaMQQ1ml2Iv0kp/UarpaOdgyS6JiQ9ydB6JZzwkRGaC5hmHmAVgo6jYLU0npSu1ZtQndalkANPo5kljqc7Ya58zfHUBmUrdSvDivHuUXnXtHSS3tIzyAXD5mpy/UGLNG5/VNZpYDtc5YvFKTmUDMBSmBSxsP881J6zzaR/4xUSpjDujej2veiHT0d+pEL0cF+mNXMYwyAzjtNqu66I1DsdJ0npSapBS9c7pZe1VPs3AYellLWG9eStr1yes4/eXq8fs0qzgFXpZUyuZ0CpIsn+3m19GmrXv8rqqDYD8jRXet67t5pT9ebgDIYAfMKt42DNL86hwTYb6KJx5ZpurQkOMSfLdjohMJ5Px9OuCbgMlsousQ=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-gateway-service
    branch: develop
